# $Id: Makefile,v 1.1.1.1 2001/01/22 12:43:59 cvsuser Exp $
#
# 2000, unicorn

MODULE = rfs

SRCS = rfs.c
SRCS+= mount_svc.c	mount_xdr.c	mount_server.c
SRCS+= nfs_prot_svc.c	nfs_prot_xdr.c	nfs_server.c
SRCS+= const.c cdir.c link.c cstring.c cint.c cint64.c flags.c enum.c
SRCS+= roomlist.c room.c exit.c

.include <../Makefile.inc>

